stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/loan_approval.csv
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
    outs:
      - models/Log.pkl

  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - models/Log.pkl
      - data/test.csv
    outs:
      - metrics/confusion_matrix.png
    metrics:
      - metrics/metrics.json:
          cache: false
