stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/loan_approval.csv
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
      - params.yaml
    outs:
      - models/model.pkl

  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - models/model.pkl
      - data/test.csv
    outs:
      - metrics/confusion_matrix.png
    metrics:
      - metrics/metrics.json
